### ISSUE TITLE
Adding default time frame to filtering meter reads

### ISSUE THREAD

**Issue by Kingcedru** [d-rec/drec-ui#165]
**Objective:**
- To Add a default time frame for filtering meter reads  on the all reads section.

**Description:**
- Add a default time frame for filtering meter reads on the all reads section.

**Acceptance Criteria:**
- Added a default time frame.
- The time frame can be customized.
- Run tests and check if everything works well.
  - The UI project runs without any issue (doesn't cause any regression error)

**Comment by divinecharlotte** [comment]
1. The ticket title 'Adding default time frame is selected when filtering meter reads' sounds confusing how about rephrasing it to something like 'Default time frame is selected when filtering meter reads'  that was my suggestion but kindly consider rephrasing it to avoid confusion 🙂 
2. This subtask **`No default time frame is selected when filtering meter reads. For the user it’s very cumbersome to filter for a meter read as all values have to be provided (which involves clicking a lot of buttons). This could be improved by populating the selected time frame by default (for example 1 month, but customisable by the user). Also, it is not possible to filter for all meter reads of a given organization.`** has two parts  which are:
-  Add a default time frame for filtering meter reads on the all reads section.
- Filtering all meta reads based on a given organization selected. You missed the second point kindly consider including it in the objective and consider updating the acceptance criteria as well because its something required to be implemented.
